/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.montage.bot;

import com.romvoid.config.COption;

public class Config {
	
	@COption
	public static String BOT_TOKEN = "";
	
	@COption
	public static String BOT_COMMAND_PREFIX = "!";
}
