/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.montage.bot;

import net.rom.Cfg;

public class Config {
	
	@Cfg
	public static String BOT_TOKEN = "";
	
	@Cfg
	public static String BOT_COMMAND_PREFIX = "!";
	
	@Cfg
	public static String WEBHOOK_URL = "place-url-here";
	
	@Cfg
	public static String PATTERN = "[%d{HH:mm:ss}] [%level] %logger{0}: %msg%n";
	
	@Cfg
	public static boolean WEBOOK_CONSOLE = false;
	
	@Cfg
	public static String BOT_GUILD_ID = "NOT-USED-YET";
	
	@Cfg
	public static String JOIN_CHANNEL_ID = "join-channel-id";
	
	@Cfg
	public static String LEAVE_CHANNEL_ID = "leave-channel-id";
}
