#!/bin/bash
# Bash file for Running CryptoBot in Linux

echo "###############################"
echo "##       Running Crypto      ##"
echo "###############################"

/bin/java -Xmx128M -jar CryptoBot-1.1.8.jar